const assert = require('node:assert/strict');
const {OperationClock} = require('../static/annotation_workbench/operation-timer.js');
let now = 0;
const clock = new OperationClock({now:() => now});
clock.setMode('pre-quality');
now = 29000;
assert.equal(clock.running, true);
assert.equal(clock.elapsed(), 29000);
now = 45000;
assert.equal(clock.running, false);
assert.equal(clock.elapsed(), 30000, '无操作只累计前 30 秒');
clock.activity();
now = 50000;
assert.equal(clock.elapsed(), 35000, '恢复操作不累计暂停期间');
clock.setMode('segments');
now = 55000;
assert.equal(clock.elapsed(), 5000);
assert.equal(clock.elapsed('pre-quality'), 35000, '切换后原模式停止累计');
clock.setVisible(false);
now = 90000;
assert.equal(clock.elapsed(), 5000, '后台时间不累计');
clock.setVisible(true);
now = 94000;
clock.setMode('action');
assert.equal(clock.elapsed('segments'), 9000);
now = 97000;
clock.setMode('log');
now = 99000;
assert.equal(clock.running, false);
assert.equal(clock.elapsed('action'), 3000);
assert.equal(new OperationClock({totals:clock.totals}).elapsed('pre-quality'), 35000, '计时可以独立恢复');
console.log('Operation timer: idle cutoff, resume, separate modes, background pause and restore passed');
