const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const rules=require('../static/annotation_workbench/semantic-quality-ranges.js');
const bad=rules.merge([{start:10,end:20},{start:15,end:25},{start:40,end:50}]);
assert.deepEqual(bad,[{start:10,end:25},{start:40,end:50}]);
assert.equal(rules.contains(bad,18),true);assert.equal(rules.contains(bad,10),false);
assert.equal(rules.overlaps(bad,5,10),false);assert.equal(rules.overlaps(bad,5,30),true);
assert.equal(rules.clip(bad,60,70),'');assert.match(rules.clip(bad,0,100),/polygon\(evenodd/);
assert.deepEqual(rules.merge([{start:-5,end:3},{start:99,end:110},{start:NaN,end:5}]),[{start:0,end:3},{start:99,end:100}]);
const registry=new Map();class HTMLElement{};
const context=vm.createContext({HTMLElement,URL,navigator:{platform:'Mac'},location:{href:'http://localhost/'},document:{currentScript:null,querySelector:()=>null},window:{WorkbenchQualityRanges:rules},customElements:{get:n=>registry.get(n),define:(n,t)=>registry.set(n,t)}});
vm.runInContext(fs.readFileSync('static/annotation_workbench/components.js','utf8'),context);
const Selector=registry.get('timeline-range-selector'),selector=new Selector();
for(const key of ['_fill','_startHandle','_endHandle','_startLabel','_endLabel'])selector[key]={style:{}};
selector._layoutLabels=()=>{};selector._rejectedRanges=bad;selector._rail={clientWidth:1000};
selector.setRange(5,70);
assert.equal(selector._start,5);assert.equal(selector._end,70,'范围选择可跨越不合格区间');
selector.setRange(13,18);assert.equal(selector._start,13);assert.equal(selector._end,18,'可自由拉到不合格区间内部');
selector.setSnapPoints([30]);assert.equal(selector._snap(9.8).value,10,'靠近不合格开始边缘时吸附');
assert.equal(selector._snap(25.3).value,25,'靠近结束边缘时吸附');assert.equal(selector._snap(18).value,18,'内部正常拖动');
console.log('Semantic rejected ranges: child clipping, split exclusion, freely draggable range and edge snapping passed');
